api_platform:
    title: 'OmPlayer API'
    version: '1.0.0'
    formats:
        json: ['application/json']
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    use_symfony_listeners: true
