security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser:
            algorithm: plaintext
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        admin_users:
            memory:
                users:
                    '%env(ADMIN_USERNAME)%':
                        password: '%env(ADMIN_PASSWORD)%'
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build|media)/
            security: false
        admin:
            pattern: ^/admin
            lazy: true
            provider: admin_users
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                default_target_path: admin
                enable_csrf: true
            logout:
                path: app_admin_logout
                target: web_home
        main:
            lazy: true
            security: false

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\InMemoryUser:
                algorithm: plaintext
